insert into ims_test.customers(first_name, surname) values('chris', 'perrins');
insert into ims_test.customers(first_name, surname) values('rhys', 'thompson');
insert into ims_test.customers(first_name, surname) values('nic', 'johnson');
insert into ims_test.customers(first_name, surname) values('jordon', 'harrison');
insert into ims_test.items(itemName,itemPrice) values("candle","5.0");
insert into ims_test.items(itemName,itemPrice) values("plant","12.0");
insert into ims_test.items(itemName,itemPrice) values("chair","30.0");
insert into ims_test.items(itemName,itemPrice) values("table","50.0");
insert into ims_test.orders(customerID,totalPrice) values(1L,50.0);
insert into ims_test.orders(customerID,totalPrice) values(3L,30.0);
insert into ims_test.orders(customerID,totalPrice) values(2L,75.0);
insert into ims_test.orders(customerID,totalPrice) values(4L,15.0);
insert into ims_test.orderline(itemID,orderID,quantity) values(1L,1L,3);
insert into ims_test.orderline(itemID,orderID,quantity) values(2L,1L,1);
insert into ims_test.orderline(itemID,orderID,quantity) values(3L,2L,2);
insert into ims_test.orderline(itemID,orderID,quantity) values(4L,2L,1);